@port = 5121
@host = http://localhost:{{port}}

PUT {{host}}/api/order/01a09958-3ac1-71e3-a980-12ee33384caa/status
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0ZDEyOTM2OC02MjZiLTRmNmUtOGYzZS1lNmQzZTI2ZjA5YmUiLCJlbWFpbCI6ImdvcmRvbi5ldmVyeXdoZXJlQGV4YW1wbGUuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjpbIlZlbmRvciIsIkN1c3RvbWVyIl0sImV4cCI6MTc4OTg4MjUwNywiaXNzIjoiRm9vZERlbGl2ZXJ5QXBpIiwiYXVkIjoiRm9vZERlbGl2ZXJ5Q2xpZW50In0.2NLwnQOEKe-WB2tMz6x2ZiTkzV1qFNHmhYE9OGN7ZLw
Content-Type: application/json

{ "status": 2 }


### Claim Order
PUT {{host}}/api/driver/01a0994d-af7e-7c47-be16-883cc20f35aa/claim
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5YzQyODJlYi0xYzZhLTQ4YzYtODc0YS1lZjdjOWI3YTViZWEiLCJlbWFpbCI6IlNoYXJvbkBNYXMuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiRHJpdmVyIiwiZXhwIjoxNzg5ODgzODM0LCJpc3MiOiJGb29kRGVsaXZlcnlBcGkiLCJhdWQiOiJGb29kRGVsaXZlcnlDbGllbnQifQ.pZYvcaCUktDUrDcWf1QtXot9C2M-oyOr2i5WGPLdi98


### Update to Delivered
PUT {{host}}/api/driver/01a0994d-af7e-7c47-be16-883cc20f35aa/status
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5YzQyODJlYi0xYzZhLTQ4YzYtODc0YS1lZjdjOWI3YTViZWEiLCJlbWFpbCI6IlNoYXJvbkBNYXMuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiRHJpdmVyIiwiZXhwIjoxNzg5ODgzODM0LCJpc3MiOiJGb29kRGVsaXZlcnlBcGkiLCJhdWQiOiJGb29kRGVsaXZlcnlDbGllbnQifQ.pZYvcaCUktDUrDcWf1QtXot9C2M-oyOr2i5WGPLdi98
Content-Type: application/json

{ "status": 4 }