@port = 5121
@host = http://localhost:{{port}}


### Place an Order (Requires Customer JWT)
POST {{host}}/api/order
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZDBhNDU5Zi00M2ZjLTQyM2ItOTgyOS00YjJmYjYzMGY5NjUiLCJlbWFpbCI6InZhcnNoYUByYW5hLmNvbSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6WyJWZW5kb3IiLCJDdXN0b21lciJdLCJleHAiOjE3OTAzNTQyNzEsImlzcyI6IkZvb2REZWxpdmVyeUFwaSIsImF1ZCI6IkZvb2REZWxpdmVyeUNsaWVudCJ9.7cNKqDCLHk99XtCm-oEMjdqN7bSnloMKkCNTLXBvF3A

{
  "restaurantId": "01a0b4ce-5993-74aa-84f1-e2159ca68238",
  "addressId":"01a0b529-9801-76bc-9dad-bdfe5b73c4fc",
  "items": [
    {
      "menuItemId": "01a0b4ce-936f-7381-b88b-11bd945aab90",
      "quantity": 2
    }
  ]
}



### Get Customer Order History (Requires Customer JWT)
GET {{host}}/api/order/customer
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZDBhNDU5Zi00M2ZjLTQyM2ItOTgyOS00YjJmYjYzMGY5NjUiLCJlbWFpbCI6InZhcnNoYUByYW5hLmNvbSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6WyJWZW5kb3IiLCJDdXN0b21lciJdLCJleHAiOjE3OTAzNTE1NDYsImlzcyI6IkZvb2REZWxpdmVyeUFwaSIsImF1ZCI6IkZvb2REZWxpdmVyeUNsaWVudCJ9.H2iokYgJsdf7pL1aqMoALAP0VVLJwdE5CEGLtArQ_c0


### Get Vendor Incoming Orders (Requires Vendor/Gordon JWT)
GET {{host}}/api/order/vendor
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0ZDEyOTM2OC02MjZiLTRmNmUtOGYzZS1lNmQzZTI2ZjA5YmUiLCJlbWFpbCI6ImdvcmRvbi5ldmVyeXdoZXJlQGV4YW1wbGUuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjpbIlZlbmRvciIsIkN1c3RvbWVyIl0sImV4cCI6MTc4OTg4MjUwNywiaXNzIjoiRm9vZERlbGl2ZXJ5QXBpIiwiYXVkIjoiRm9vZERlbGl2ZXJ5Q2xpZW50In0.2NLwnQOEKe-WB2tMz6x2ZiTkzV1qFNHmhYE9OGN7ZLw


### Update Order Status to Accepted (Requires Vendor JWT)
PUT {{host}}/api/order/01a0994d-af7e-7c47-be16-883cc20f35aa/status
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0ZDEyOTM2OC02MjZiLTRmNmUtOGYzZS1lNmQzZTI2ZjA5YmUiLCJlbWFpbCI6ImdvcmRvbi5ldmVyeXdoZXJlQGV4YW1wbGUuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjpbIlZlbmRvciIsIkN1c3RvbWVyIl0sImV4cCI6MTc4OTg4MjUwNywiaXNzIjoiRm9vZERlbGl2ZXJ5QXBpIiwiYXVkIjoiRm9vZERlbGl2ZXJ5Q2xpZW50In0.2NLwnQOEKe-WB2tMz6x2ZiTkzV1qFNHmhYE9OGN7ZLw

{
  "status": 1
}