@port = 5121

@host = http://localhost:{{port}}

### Get all restaurants and their menus (Public)
GET {{host}}/api/restaurant

### Get all menus of specific restaurant (Public)
GET {{host}}/api/menuitem/01a0b4ce-5993-74aa-84f1-e2159ca68238


### Create a Restaurant (Requires Vendor JWT)
POST {{host}}/api/restaurant
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkMzRhMWExZC05OTA1LTRiYmQtOGY3Mi1iMDEyZWViYzJlZDAiLCJlbWFpbCI6ImdvcmRvbi5ldmVyeXdoZXJlQGV4YW1wbGUuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjpbIlZlbmRvciIsIkN1c3RvbWVyIl0sImV4cCI6MTc5MDU3NjMwNSwiaXNzIjoiRm9vZERlbGl2ZXJ5QXBpIiwiYXVkIjoiRm9vZERlbGl2ZXJ5Q2xpZW50In0.Ovj9kuPxLrcT2eUlxKvslbKhc2xR_ndArUUXUhMf8jU

{
  "name": "Amritsari Restaurant",
  "FullAddress": "Fatehgunj mein in front of Zudio",
  "city":"Vadodara",
  "pinCode":"390009"
}



### Add a Menu Item (Requires Vendor/Gordon's JWT)
POST {{host}}/api/menuitem
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkMzRhMWExZC05OTA1LTRiYmQtOGY3Mi1iMDEyZWViYzJlZDAiLCJlbWFpbCI6ImdvcmRvbi5ldmVyeXdoZXJlQGV4YW1wbGUuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjpbIlZlbmRvciIsIkN1c3RvbWVyIl0sImV4cCI6MTc5MDU3NjMwNSwiaXNzIjoiRm9vZERlbGl2ZXJ5QXBpIiwiYXVkIjoiRm9vZERlbGl2ZXJ5Q2xpZW50In0.Ovj9kuPxLrcT2eUlxKvslbKhc2xR_ndArUUXUhMf8jU

{
  "name": "Beef Wellington",
  "description": "A prime fillet of beef wrapped in puff pastry.",
  "category":"",
  "price": 45.99,
  "restaurantId": "01a0c29d-dbd9-758c-a4d0-1344b237992a"
}



### Add a Categorized Menu Item (Requires Vendor JWT)
POST {{host}}/api/menuitem
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkMzRhMWExZC05OTA1LTRiYmQtOGY3Mi1iMDEyZWViYzJlZDAiLCJlbWFpbCI6ImdvcmRvbi5ldmVyeXdoZXJlQGV4YW1wbGUuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjpbIlZlbmRvciIsIkN1c3RvbWVyIl0sImV4cCI6MTc5MDU3NjMwNSwiaXNzIjoiRm9vZERlbGl2ZXJ5QXBpIiwiYXVkIjoiRm9vZERlbGl2ZXJ5Q2xpZW50In0.Ovj9kuPxLrcT2eUlxKvslbKhc2xR_ndArUUXUhMf8jU

{
  "name": "Masala Dosa",
  "description": "Crispy crepe stuffed with spiced potatoes.",
  "price": 120.00,
  "category": "Dosa",
  "dietaryPreference": 0,
  "restaurantId": "01a0c2a1-a244-79fb-9603-9f1c2aea0293"
}