@port = 5121
@host = http://localhost:{{port}}

### Register Multi-Role User
POST {{host}}/api/auth/register
Content-Type: application/json

{
  "email": "gordon.everywhere@example.com",
  "password": "Password123!",
  "fullName": "Gordon Ramsay",
  "roles": ["Vendor", "Customer"]
}

### Login as gordon
POST {{host}}/api/auth/login
Content-Type: application/json

{
  "email": "gordon.everywhere@example.com",
  "password": "Password123!"
}

### Login as varsha
POST {{host}}/api/auth/login
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "Password123!"
}


### Create a Restaurant (Requires Vendor JWT)
POST {{host}}/api/restaurant
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4NTEyZDg0My0xNTVhLTQyMWYtOTQ1NC1hNzU5NjVlYTkxNmQiLCJlbWFpbCI6ImdvcmRvbi5ldmVyeXdoZXJlQGV4YW1wbGUuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjpbIlZlbmRvciIsIkN1c3RvbWVyIl0sImV4cCI6MTc4OTc0OTAzNCwiaXNzIjoiRm9vZERlbGl2ZXJ5QXBpIiwiYXVkIjoiRm9vZERlbGl2ZXJ5Q2xpZW50In0.EVkwG7LxuHDUSBRalV_i6WKq7P2ts3WmtstNgy91-Lw

{
  "name": "The Royal Gordon Ramsay Hotel",
  "address": "Las Vegas Blvd"
}

### Add a Menu Item (Requires Gordon's JWT)
POST {{host}}/api/menuitem
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4NTEyZDg0My0xNTVhLTQyMWYtOTQ1NC1hNzU5NjVlYTkxNmQiLCJlbWFpbCI6ImdvcmRvbi5ldmVyeXdoZXJlQGV4YW1wbGUuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjpbIlZlbmRvciIsIkN1c3RvbWVyIl0sImV4cCI6MTc4OTc0OTAzNCwiaXNzIjoiRm9vZERlbGl2ZXJ5QXBpIiwiYXVkIjoiRm9vZERlbGl2ZXJ5Q2xpZW50In0.EVkwG7LxuHDUSBRalV_i6WKq7P2ts3WmtstNgy91-Lw

{
  "name": "Beef Wellington",
  "description": "A prime fillet of beef wrapped in puff pastry.",
  "price": 45.99,
  "restaurantId": "01a0914f-6cc7-79e8-b217-dcb310df786b"
}


### Get all restaurants and their menus (Public)
GET {{host}}/api/restaurant


### Place an Order (Requires Customer JWT)
POST {{host}}/api/order
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiYTEyZjAyNi1iMTYxLTQwMGEtODQ0Mi01ZjBlZGQ0NzgyMTgiLCJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJDdXN0b21lciIsImV4cCI6MTc4OTc0OTEyNSwiaXNzIjoiRm9vZERlbGl2ZXJ5QXBpIiwiYXVkIjoiRm9vZERlbGl2ZXJ5Q2xpZW50In0.uox84LZJnBq4VCyHFEZhOb0MjZc9jhMn97HRQmeIit0

{
  "restaurantId": "01a0914f-6cc7-79e8-b217-dcb310df786b",
  "items": [
    {
      "menuItemId": "01a09150-66d6-79ae-b680-e99eddc5fba9",
      "quantity": 2
    }
  ]
}

### Get Customer Order History (Requires Customer JWT)
GET {{host}}/api/order/customer
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiYTEyZjAyNi1iMTYxLTQwMGEtODQ0Mi01ZjBlZGQ0NzgyMTgiLCJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJDdXN0b21lciIsImV4cCI6MTc4OTc0OTE5NywiaXNzIjoiRm9vZERlbGl2ZXJ5QXBpIiwiYXVkIjoiRm9vZERlbGl2ZXJ5Q2xpZW50In0.qI3U7r3PNfMAQkbsfOwO_BH-6IQUXnIs1xjoYkN-cMM

### Get Vendor Incoming Orders (Requires Vendor/Gordon JWT)
GET {{host}}/api/order/vendor
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4NTEyZDg0My0xNTVhLTQyMWYtOTQ1NC1hNzU5NjVlYTkxNmQiLCJlbWFpbCI6ImdvcmRvbi5ldmVyeXdoZXJlQGV4YW1wbGUuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjpbIlZlbmRvciIsIkN1c3RvbWVyIl0sImV4cCI6MTc4OTc0OTIzMiwiaXNzIjoiRm9vZERlbGl2ZXJ5QXBpIiwiYXVkIjoiRm9vZERlbGl2ZXJ5Q2xpZW50In0.R1hCufmHcLnNO1hZIVptHuE-CoSatgLHEv3AjqL51JA

### Update Order Status to Accepted (Requires Vendor JWT)
PUT {{host}}/api/order/01a09150-a51e-7ab2-94b2-9f800fa71741/status
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4NTEyZDg0My0xNTVhLTQyMWYtOTQ1NC1hNzU5NjVlYTkxNmQiLCJlbWFpbCI6ImdvcmRvbi5ldmVyeXdoZXJlQGV4YW1wbGUuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjpbIlZlbmRvciIsIkN1c3RvbWVyIl0sImV4cCI6MTc4OTc0OTMwNywiaXNzIjoiRm9vZERlbGl2ZXJ5QXBpIiwiYXVkIjoiRm9vZERlbGl2ZXJ5Q2xpZW50In0.GN2_Jzi6dIRB4eLisvc75cAI6l3uZUpKplNoTrwHsoA

{
  "status": 1
}