@port = 5121
@host = http://localhost:{{port}}

### Register a new Customer
POST {{host}}/api/auth/register
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "Password123!",
  "fullName": "Varsha Rana",
  "role": 0
}